name = "tunc"
main = "src/index.ts"
compatibility_date = "2025-08-05"
compatibility_flags = ["nodejs_compat"]
account_id = "1e54c42267499cd9093c467c8b5517d1"

[vars]
ALLOWED_ORIGINS = "https://example.com"
MAX_UPLOAD_SIZE = "10485760"
SLACK_CHANNEL = "#general"

[[d1_databases]]
binding = "DB"
database_name = "tunc_db"
database_id = "315bf476-04e5-401a-af8f-8eefc1b8a8dc"

[durable_objects]
bindings = [
  { name = "TIMELINE_DO", class_name = "TimelineDO" }
]

[[migrations]]
tag = "v1"
new_classes = [ "TimelineDO" ]

[[queues.producers]]
binding = "NOTIFY_QUEUE"
queue = "tunc_notify"

[[queues.consumers]]
queue = "tunc_notify"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "tunc-media"
preview_bucket_name = "tunc-media-preview"

[env.production]
[env.production.workers.notify]
main = "src/notify.ts"


[env.production.vars]
ALLOWED_ORIGINS = "https://example.com" # Replace with production value if different
MAX_UPLOAD_SIZE = "10485760" # Replace with production value if different
SLACK_CHANNEL = "#general" # Replace with production value if different

[env.production.durable_objects]
bindings = [
  { name = "TIMELINE_DO", class_name = "TimelineDO" }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "tunc-db" 
database_id = "315bf476-04e5-401a-af8f-8eefc1b8a8dc" 

[[env.production.queues.producers]]
binding = "NOTIFY_QUEUE"
queue = "tunc-notify-production" 

[[env.production.queues.consumers]]
queue = "tunc-notify-production" 

[[env.production.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "tunc-media-production" # Replace with production bucket name
preview_bucket_name = "tunc-media-preview-production" # Replace with production preview bucket name