name = "tunc"
main = "src/index.ts"
compatibility_date = "2025-08-05"
compatibility_flags = ["nodejs_compat"]

[workers.notify]
main = "src/notify.ts"

# TODO: Set your Cloudflare account ID before deploying
# account_id = "your-account-id"

[[d1_databases]]
binding = "DB"
database_name = "tunc_db"
database_id = "315bf476-04e5-401a-af8f-8eefc1b8a8dc"

[[durable_objects]]
bindings = [ { name = "TIMELINE_DO", class_name = "Timeline" } ]


[[queues.producers]]
binding = "NOTIFY_QUEUE"
queue = "tunc_notify"

[[queues.consumers]]
queue = "tunc_notify"
worker = "notify"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "tunc-media"
preview_bucket_name = "tunc-media-preview"
